name: gptui

services:
  gptui:
    image: gptui
    build:
      context: .
      target: dev
    container_name: gptui
    restart: always
    networks:
      - gptui
    volumes:
      - gptui:/home/node/vite
      - ~/.ssh:/root/.ssh:ro

networks:
  gptui:
    name: gptui

volumes:
  gptui:
    name: gptui
