name: gptui

services:
  gptui:
    image: gptui
    build: .
    container_name: gptui
    restart: always
    networks:
      - gptui
    volumes:
      - gptui:/var/www/vite
      - ~/.ssh:/root/.ssh:ro

networks:
  gptui:
    name: gptui

volumes:
  gptui:
    name: gptui
