name: gptui

services:
  gptui:
    image: gptui
    build: .
    container_name: gptui
    restart: always
    networks:
      - gptui
    volumes:
      - gptui:/home/node/vite
      - ~/.ssh:/root/.ssh:ro
    ports:
      - 5173:5173

networks:
  gptui:
    name: gptui

volumes:
  gptui:
    name: gptui
