name: likeadmin

networks:
  likeadmin:
    name: likeadmin

services:
  nginx:
    container_name: likeadmin-nginx
    image: nginx:alpine
    restart: always
    depends_on:
      - "php"
    volumes:
      - ../server:/likeadmin_php/server
      - ./config/nginx/conf.d/www.likeadmin.host.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx/logs:/logs
    networks:
      - likeadmin
    ports:
      - "80:80"

  php:
    container_name: likeadmin-php
    build: .
    restart: always
    working_dir: /likeadmin_php/server
    volumes:
      - ../server:/likeadmin_php/server
    networks:
      - likeadmin

  mariadb:
    container_name: likeadmin-mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./data/mariadb/lib:/var/lib/mysql
      - ./config/mysql/mysqld.cnf:/etc/mysql/my.cnf
    networks:
      - likeadmin


  redis:
    container_name: likeadmin-redis
    image: redis:alpine
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - likeadmin

  node:
    container_name: likeadmin-node
    image: node:alpine
    restart: always
    volumes:
      - ../admin:/likeadmin_php/admin
    networks:
      - likeadmin
    tty: true
    working_dir: /likeadmin_php/admin
    ports:
      - "5173:5173"
